BEGIN;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0);

CREATE TABLE IF NOT EXISTS inventory_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id),
  variant_id BIGINT REFERENCES product_variants(id),
  admin_id BIGINT NOT NULL REFERENCES users(id),
  change_type VARCHAR(20) NOT NULL CHECK (change_type IN ('CREATE','SET','INCREASE','DECREASE')),
  quantity_before DECIMAL(12,3) NOT NULL,
  quantity_change DECIMAL(12,3) NOT NULL,
  quantity_after DECIMAL(12,3) NOT NULL CHECK (quantity_after >= 0),
  reason VARCHAR(240) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_inventory_audit_product_time ON inventory_audit(product_id,created_at DESC);

CREATE TABLE IF NOT EXISTS order_assignment_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id),
  previous_agent_id BIGINT REFERENCES agents(id),
  new_agent_id BIGINT NOT NULL REFERENCES agents(id),
  admin_id BIGINT REFERENCES users(id),
  action VARCHAR(20) NOT NULL CHECK (action IN ('AUTO_ASSIGN','MANUAL_ASSIGN','REASSIGN')),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_assignment_audit_order_time ON order_assignment_audit(order_id,created_at DESC);

SELECT setval(pg_get_serial_sequence('carts','id'),COALESCE((SELECT MAX(id) FROM carts),1));

COMMIT;
