BEGIN;

DROP VIEW IF EXISTS agent_performance_view;
DROP VIEW IF EXISTS active_orders_view;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE order_status_log DROP CONSTRAINT IF EXISTS order_status_log_status_check;
ALTER TABLE orders ALTER COLUMN status TYPE VARCHAR(24);
ALTER TABLE order_status_log ALTER COLUMN status TYPE VARCHAR(24);
UPDATE orders SET status='OUT_FOR_DELIVERY' WHERE status='IN_TRANSIT';
UPDATE order_status_log SET status='OUT_FOR_DELIVERY' WHERE status='IN_TRANSIT';
ALTER TABLE orders ADD CONSTRAINT orders_status_check CHECK (status IN
  ('SCHEDULED','PLACED','CONFIRMED','PACKED','ASSIGNED','PICKED_UP','OUT_FOR_DELIVERY','DELIVERY_VERIFICATION','DELIVERED','CANCELLED'));
ALTER TABLE order_status_log ADD CONSTRAINT order_status_log_status_check CHECK (status IN
  ('SCHEDULED','PLACED','CONFIRMED','PACKED','ASSIGNED','PICKED_UP','OUT_FOR_DELIVERY','DELIVERY_VERIFICATION','DELIVERED','CANCELLED'));

ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_code_hash VARCHAR(180);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_code_ciphertext VARCHAR(200);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_code_fingerprint CHAR(64);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_code_expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_code_verified_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_code_verified_by BIGINT REFERENCES users(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_code_verification_role VARCHAR(10)
  CHECK (delivery_code_verification_role IN ('AGENT','ADMIN'));
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_code_failed_attempts INTEGER NOT NULL DEFAULT 0
  CHECK (delivery_code_failed_attempts BETWEEN 0 AND 5);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_code_blocked_until TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_partner_id BIGINT REFERENCES agents(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS manual_delivery_confirmation_reason VARCHAR(500);
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_delivery_code_fingerprint
  ON orders(delivery_code_fingerprint) WHERE delivery_code_fingerprint IS NOT NULL;
DROP INDEX IF EXISTS idx_orders_pending_fifo;
CREATE INDEX idx_orders_pending_fifo ON orders(created_at,id)
  WHERE status='PACKED' AND agent_id IS NULL;

CREATE TABLE IF NOT EXISTS order_security_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id),
  actor_id BIGINT NOT NULL REFERENCES users(id),
  actor_role VARCHAR(10) NOT NULL CHECK (actor_role IN ('AGENT','ADMIN')),
  action VARCHAR(40) NOT NULL CHECK (action IN
    ('DELIVERY_CODE_FAILED','DELIVERY_CODE_BLOCKED','DELIVERY_CODE_EXPIRED','DELIVERY_VERIFIED','ADMIN_DELIVERY_VERIFIED')),
  old_status VARCHAR(24) NOT NULL,
  new_status VARCHAR(24) NOT NULL,
  ip_address VARCHAR(64) NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_order_security_audit_order_time
  ON order_security_audit(order_id,created_at DESC);

CREATE VIEW active_orders_view AS
SELECT o.id,o.status,o.order_type,o.priority,o.total_weight_kg,o.pickup_address,
       o.drop_address,o.created_at,o.scheduled_delivery_at,c.name customer_name,
       a.id agent_id,au.name agent_name
FROM orders o JOIN users c ON c.id=o.customer_id
LEFT JOIN agents a ON a.id=o.agent_id LEFT JOIN users au ON au.id=a.user_id
WHERE o.status NOT IN ('DELIVERED','CANCELLED');

CREATE VIEW agent_performance_view AS
SELECT a.id agent_id,u.name agent_name,v.name vehicle_type,a.status,a.rating,
       COUNT(o.id) FILTER (WHERE o.status='DELIVERED') completed_deliveries,
       ROUND(AVG(EXTRACT(EPOCH FROM (o.delivered_at-o.created_at))/60.0)
         FILTER (WHERE o.status='DELIVERED'),1) avg_delivery_minutes
FROM agents a JOIN users u ON u.id=a.user_id
JOIN vehicle_types v ON v.id=a.vehicle_type_id LEFT JOIN orders o ON o.agent_id=a.id
GROUP BY a.id,u.name,v.name,a.status,a.rating;

COMMIT;
